version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8001'
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: c3c1t3.2o19
      MYSQL_ROOT_PASSWORD: c3c1t3.2o19
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
