from .EncuestaPlantel import EncuestaPlantel
from .OfertaEducativa import OfertaEducativa
from .PlantelEscolaridad import PlantelEscolaridad
from .PlantelEstadistica import PlantelEstadistica
from .PlantelInformacion import PlantelInformacion
from .PlantelInfraestructura import PlantelInfraestructura
from .PlantelLegal import PlantelLegal
from .PlantelVinculacion import PlantelVinculacion