from django.db import models


class PlantelInfraestructura(models.Model):
    class Meta:
        db_table = "encuesta_plantel_infraestructura"

    encuesta_id = models.AutoField(primary_key=True)
    fecha = models.DateField(null=True)
    niveles = models.CharField(max_length=150, null=True)
    superficie_total = models.CharField(max_length=150, null=True)
    superficie_libre = models.CharField(max_length=150, null=True)
    superficie_urbana = models.CharField(max_length=150, null=True)
    uso_plantel = models.CharField(max_length=150, null=True)
    conservacion = models.CharField(max_length=150, null=True)
    personas_laboran = models.IntegerField(null=True)
    aulas_tiene = models.BooleanField(default=1, null=True)
    aulas_funcionalidad = models.CharField(max_length=150, null=True)
    aulas_cantidad = models.IntegerField(null=True)
    laboratorios_tiene = models.BigIntegerField(null=True)
    laboratorios_funcionalidad = models.CharField(max_length=150, null=True)
    laboratorios_cantidad = models.IntegerField(null=True)
    laboratorios_especificar = models.CharField(max_length=150, null=True)
    talleres_tiene = models.BooleanField(default=1, null=True)
    talleres_funcionalidad = models.CharField(max_length=150, null=True)
    talleres_cantidad = models.IntegerField(null=True)
    talleres_especificar = models.CharField(max_length=150, null=True)
    salon_usos_multiple_tiene = models.BooleanField(default=1, null=True)
    salon_usos_multiple_funcionalidad = models.CharField(max_length=150, null=True)
    auditorio_tiene = models.BooleanField(default=1, null=True)
    auditorio_funcionalidad = models.CharField(max_length=150, null=True)
    biblioteca_tiene = models.BooleanField(default=1, null=True)
    biblioteca_funcionalidad = models.CharField(max_length=150, null=True)
    plaza_civica_tiene = models.BooleanField(default=1, null=True)
    plaza_civica_funcionalidad = models.CharField(max_length=150, null=True)
    plaza_civica_techada = models.CharField(max_length=150, null=True)
    plaza_civica_tipo = models.CharField(max_length=150, null=True)
    jardineras_tiene = models.BigIntegerField(null=True)
    jardineras_funcionalidad = models.CharField(max_length=150, null=True)
    areas_verdes_tiene = models.BooleanField(default=1, null=True)
    areas_verdes_funcionalidad = models.CharField(max_length=150, null=True)
    areas_verdes_metros = models.CharField(max_length=150, null=True)
    bebederos_tiene = models.BooleanField(default=1, null=True)
    bebederos_funcionalidad = models.CharField(max_length=150, null=True)
    rampa_tiene = models.BooleanField(default=1, null=True)
    rampa_funcionalidad = models.CharField(max_length=150, null=True)
    deportivas_tiene = models.BooleanField(default=1, null=True)
    deportivas_funcionalidad = models.CharField(max_length=150, null=True)
    futbol_soccer_tiene = models.BooleanField(default=1, null=True)
    futbol_soccer_funcionalidad = models.CharField(max_length=150, null=True)
    futbol_rapido_tiene = models.BooleanField(default=1, null=True)
    futbol_rapido_funcionalidad = models.CharField(max_length=150, null=True)
    basquetbol_tiene = models.BooleanField(default=1, null=True)
    basquetbol_funcionalidad = models.CharField(max_length=150, null=True)
    andadores_tiene = models.BooleanField(default=1, null=True)
    andadores_funcionalidad = models.CharField(max_length=150, null=True)
    andadores_cantidad = models.CharField(max_length=150, null=True)
    portico_tiene = models.BooleanField(default=1, null=True)
    portico_funcionalidad = models.CharField(max_length=150, null=True)
    cafeteria_tiene = models.BooleanField(default=1, null=True)
    cafeteria_funcionalidad = models.CharField(max_length=150, null=True)
    edificios_tiene = models.BooleanField(default=1, null=True)
    edificios_funcionalidad = models.CharField(max_length=150, null=True)
    modulos_administrativos_tiene = models.BooleanField(default=1, null=True)
    direccion_tiene = models.BooleanField(default=1, null=True)
    direccion_funcionalidad = models.CharField(max_length=150, null=True)
    control_escolar_tiene = models.BooleanField(default=1, null=True)
    control_escolar_funcionalidad = models.CharField(max_length=150, null=True)
    servicio_social_tiene = models.BooleanField(default=1, null=True)
    servicio_social_funcionalidad = models.CharField(max_length=150, null=True)
    prefectura_tiene = models.BooleanField(default=1, null=True)
    prefectura_funcionalidad = models.CharField(max_length=150, null=True)
    area_administrativa_tiene = models.BooleanField(default=1, null=True)
    area_administrativa_funcionalidad = models.CharField(max_length=150, null=True)
    area_academica_tiene = models.BooleanField(default=1, null=True)
    area_academica_funcionalidad = models.CharField(max_length=150, null=True)
    area_planeacion_tiene = models.BooleanField(default=1, null=True)
    area_planeacion_funcionalidad = models.CharField(max_length=150, null=True)
    area_vinculacion_tiene = models.BooleanField(default=1, null=True)
    area_vinculacion_funcionalidad = models.CharField(max_length=150, null=True)
    area_estres_tiene = models.BooleanField(default=1, null=True)
    area_estres_funcionalidad = models.CharField(max_length=150, null=True)
    sala_maestros_tiene = models.BooleanField(default=1, null=True)
    sala_maestros_funcionalidad = models.CharField(max_length=150, null=True)
    cerco_perimetral_tiene = models.BooleanField(default=1, null=True)
    cerco_perimetral_funcionalidad = models.CharField(max_length=150, null=True)
    cerco_perimetral_tipo = models.CharField(max_length=150, null=True)
    cerco_perimetral_metros = models.CharField(max_length=150, null=True)
    puertas_tiene = models.BooleanField(default=1, null=True)
    puertas_funcionalidad = models.CharField(max_length=150, null=True)
    caseta_vigilancia_tiene = models.BooleanField(default=1, null=True)
    caseta_vigilancia_funcionalidad = models.CharField(max_length=150, null=True)
    sistema_hidro_tiene = models.BooleanField(default=1, null=True)
    sistema_hidro_funcionalidad = models.CharField(max_length=150, null=True)
    estacion_elec_tiene = models.BooleanField(default=1, null=True)
    estacion_elec_funcionalidad = models.CharField(max_length=150, null=True)
    transformador_tiene = models.BooleanField(default=1, null=True)
    transformador_funcionalidad = models.CharField(max_length=150, null=True)
    tablero_tiene = models.BooleanField(default=1, null=True)
    tablero_funcionalidad = models.CharField(max_length=150, null=True)
    planta_energia_tiene = models.BooleanField(default=1, null=True)
    planta_energia_funcionalidad = models.CharField(max_length=150, null=True)
    cisterna_tiene = models.BooleanField(default=1, null=True)
    cisterna_funcionalidad = models.CharField(max_length=150, null=True)
    aire_tiene = models.BooleanField(default=1, null=True)
    aire_funcionalidad = models.CharField(max_length=150, null=True)
    minisplit_tiene = models.BooleanField(default=1, null=True)
    minisplit_funcionalidad = models.CharField(max_length=150, null=True)
    minisplit_cuantos = models.CharField(max_length=150, null=True)
    calefaccion_tiene = models.BooleanField(default=1, null=True)
    calefaccion_funcionalidad = models.CharField(max_length=150, null=True)
    calefaccion_cuantos = models.CharField(max_length=150, null=True)
    incendio_tiene = models.BooleanField(default=1, null=True)
    incendio_funcionalidad = models.CharField(max_length=150, null=True)
    incendio_cuantos = models.CharField(max_length=150, null=True)
    bombeo_tiene = models.BooleanField(default=1, null=True)
    bombeo_funcionalidad = models.CharField(max_length=150, null=True)
    bombeo_cuantos = models.CharField(max_length=150, null=True)
    humo_tiene = models.BooleanField(default=1, null=True)
    humo_funcionalidad = models.CharField(max_length=150, null=True)
    sismo_tiene = models.BooleanField(default=1, null=True)
    sismo_funcionalidad = models.CharField(max_length=150, null=True)
    sanitarios_estudiantes_tiene = models.BooleanField(default=1, null=True)
    sanitarios_estudiantes_funcionalidad = models.CharField(max_length=150, null=True)
    sanitarios_estudiantes_hombre = models.IntegerField(null=True)
    sanitarios_estudiantes_mujer = models.IntegerField(null=True)
    sanitarios_docentes_tiene = models.BooleanField(default=1, null=True)
    sanitarios_docentes_funcionalidad = models.CharField(max_length=150, null=True)
    sanitarios_docentes_hombre = models.IntegerField(null=True)
    sanitarios_docentes_mujer = models.IntegerField(null=True)
    sanitarios_administrativos_tiene = models.BooleanField(default=1, null=True)
    sanitarios_administrativos_funcionalidad = models.CharField(
        max_length=150, null=True
    )
    sanitarios_administrativos_hombre = models.IntegerField(null=True)
    sanitarios_administrativos_mujer = models.IntegerField(null=True)
    fosa_tiene = models.BooleanField(default=1, null=True)
    fosa_funcionalidad = models.CharField(max_length=150, null=True)
    pozo_tiene = models.BooleanField(default=1, null=True)
    pozo_funcionalidad = models.CharField(max_length=150, null=True)
    drenaje_tiene = models.BooleanField(default=1, null=True)
    drenaje_funcionalidad = models.CharField(max_length=150, null=True)
