from django.db import models


class PlantelEscolaridad(models.Model):
    class Meta:
        db_table = "encuesta_plantel_escolaridad"

    encuesta_id = models.AutoField(primary_key=True)
    fecha = models.DateField(null=True)
    directivo_doctorado = models.IntegerField(null=True)
    docente_doctorado = models.IntegerField(null=True)
    administrativo_doctorado = models.IntegerField(null=True)
    servicios_doctorado = models.IntegerField(null=True)
    directivo_maestria = models.IntegerField(null=True)
    docente_maestria = models.IntegerField(null=True)
    administrativo_maestria = models.IntegerField(null=True)
    servicios_maestria = models.IntegerField(null=True)
    directivo_especializacion = models.IntegerField(null=True)
    docente_especializacion = models.IntegerField(null=True)
    administrativo_especializacion = models.IntegerField(null=True)
    servicios_especializacion = models.IntegerField(null=True)
    directivo_licenciatura = models.IntegerField(null=True)
    docente_licenciatura = models.IntegerField(null=True)
    administrativo_licenciatura = models.IntegerField(null=True)
    servicios_licenciatura = models.IntegerField(null=True)
    directivo_superior = models.IntegerField(null=True)
    docente_superior = models.IntegerField(null=True)
    administrativo_superior = models.IntegerField(null=True)
    servicios_superior = models.IntegerField(null=True)
    directivo_superior_maestros = models.IntegerField(null=True)
    docente_superior_maestros = models.IntegerField(null=True)
    administrativo_superior_maestros = models.IntegerField(null=True)
    servicios_superior_maestros = models.IntegerField(null=True)
    directivo_bachillerato = models.IntegerField(null=True)
    docente_bachillerato = models.IntegerField(null=True)
    administrativo_bachillerato = models.IntegerField(null=True)
    servicios_bachillerato = models.IntegerField(null=True)
    directivo_tecnico = models.IntegerField(null=True)
    docente_tecnico = models.IntegerField(null=True)
    administrativo_tecnico = models.IntegerField(null=True)
    servicios_tecnico = models.IntegerField(null=True)
    directivo_comercial = models.IntegerField(null=True)
    docente_comercial = models.IntegerField(null=True)
    administrativo_comercial = models.IntegerField(null=True)
    servicios_comercial = models.IntegerField(null=True)
    directivo_secundaria = models.IntegerField(null=True)
    docente_secundaria = models.IntegerField(null=True)
    administrativo_secundaria = models.IntegerField(null=True)
    servicios_secundaria = models.IntegerField(null=True)
    directivo_primaria = models.IntegerField(null=True)
    docente_primaria = models.IntegerField(null=True)
    administrativo_primaria = models.IntegerField(null=True)
    servicios_primaria = models.IntegerField(null=True)
