# Generated by Django 3.1.4 on 2020-12-27 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personacoordinacion',
            old_name='area_coordinacion_id',
            new_name='area_coordinacion',
        ),
    ]
