# Generated by Django 3.1.4 on 2020-12-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201227_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacoordinacion',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personacoordinacion',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
