# Generated by Django 3.1.4 on 2020-12-27 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201227_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacoordinacion',
            name='extension',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
