# Generated by Django 3.1.4 on 2020-12-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201227_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacoordinacion',
            name='cargo',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
