# Generated by Django 3.1.4 on 2020-12-28 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201227_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='personacoordinacion',
            name='imagen',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='personacoordinacion',
            name='area_coordinacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='home.areacoordinacion'),
        ),
    ]
