# Generated by Django 3.1.4 on 2020-12-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201227_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('director_general', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=50)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'persona_colegio',
            },
        ),
        migrations.AlterField(
            model_name='areacoordinacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personacoordinacion',
            name='cargo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personacoordinacion',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personacoordinacion',
            name='imagen',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personacoordinacion',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
