# Generated by Django 3.1.4 on 2020-12-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201227_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personacolegio',
            name='telefono',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
