# Generated by Django 3.1.4 on 2020-12-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20201227_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionYVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.CharField(max_length=300)),
                ('vision', models.CharField(max_length=300)),
                ('estatus', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'mision_y_vision',
            },
        ),
    ]
