# Generated by Django 3.1.4 on 2020-12-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_misionyvision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misionyvision',
            name='mision',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='misionyvision',
            name='vision',
            field=models.CharField(max_length=500),
        ),
    ]
