# Generated by Django 3.1.4 on 2020-12-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20201227_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaCecyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'pagina_cecyte',
            },
        ),
        migrations.AlterField(
            model_name='misionyvision',
            name='mision',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='misionyvision',
            name='vision',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='personacolegio',
            name='direccion',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ContenidoPagina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo_vista', models.CharField(max_length=200, null=True)),
                ('texto', models.CharField(max_length=1000, null=True)),
                ('pdf', models.CharField(max_length=200, null=True)),
                ('imagen', models.CharField(max_length=200, null=True)),
                ('estatus', models.BooleanField(default=True)),
                ('pagina_cecyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenido_pagina', to='home.paginacecyte')),
            ],
            options={
                'db_table': 'contenido_pagina',
            },
        ),
    ]
