# Generated by Django 3.1.4 on 2020-12-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20201231_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='paginacecyte',
            name='objetivo',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
