# Generated by Django 3.1.4 on 2020-12-31 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_paginacecyte_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.CharField(max_length=200)),
                ('enlace', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
    ]
