# Generated by Django 3.1.4 on 2020-12-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
